name: CI

on:
  pull_request:
  push:
    branches: master
  schedule:
    # Run at 4:08am every Monday
    - cron: "8 4 * * 1"


jobs:
  check-links:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v1
    - name: Link Checker
      id: lychee
      uses: lycheeverse/lychee-action@v1.0.8
      with:
        args: --verbose --no-progress **/*.md **/*.html

    - name: Fail on link errors in PRs
      if: ${{ github.event_name == 'pull_request' }}
      run: exit ${{ steps.lychee.outputs.exit_code }}

    - name: Create Issue
      if: ${{ github.event_name == 'schedule' }}
      uses: peter-evans/create-issue-from-file@v2
      with:
        title: Dead links detected
        content-filepath: ./lychee/out.md
        labels: 'link rot'
